[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
paytogether = "2ZzrLXe8EKYiY3BHthebN6wpC4zcP8QA1Bu1X1XE8PDF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
