import type { Metadata } from "next";

import "./globals.css";
import { Wallet } from "./components/Wallet";
import { CivicAuthProvider } from "@civic/auth/nextjs";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <CivicAuthProvider>
          <Wallet>{children}</Wallet>
        </CivicAuthProvider>
      </body>
    </html>
  );
}
